a = 32     
b = 6  
print('Addition of two numbers:',a+b)  
print('Subtraction of two numbers:',a-b)  
print('Multiplication of two numbers:',a*b)  
print('Division of two numbers:',a/b)  
print('Reminder of two numbers:',a%b)  
print('Exponent of two numbers:',a**b)  
print('Floor division of two numbers:',a//b)
print('Two numbers are equal :',a==b)  
print('Two numbers are not equal :',a!=b)  
print('a is less than or equal to b:',a<=b)  
print('a is greater than or equal to b:',a>=b)  
print('a is greater b:',a>b)  
print('a is less than b:',a<b)