# a = int(input('Enter first number:'))
# b = int(input('Enter second number:'))    

# print('Addition of two numbers:',a+b)  
# print('Subtraction of two numbers:',a-b)  
# print('Multiplication of two numbers:',a*b)  
# print('Division of two numbers:',a/b)  
# print('Reminder of two numbers:',a%b)  
# print('Exponent of two numbers:',a**b)  
# print('Floor division of two numbers:',a//b)
# print('Two numbers are equal :',a==b)  
# print('Two numbers are not equal :',a!=b)  
# print('a = less than or equal to b:',a<=b)  
# print('a = greater than or equal to b:',a>=b)  
# print('a = greater b:',a>b)  
# print('a = less than b:',a<b)

a = float(input('Enter first number: '))
b = float(input('Enter second number: '))

# print(f"Addition: {a} + {b} = {a+b}")
# print(f"Subtraction: {a} - {b} = {a-b}")
# print(f"Multiplication: {a} * {b} = {a*b}")
# print(f"Division: {a} / {b} = {a/b}")
# print(f"Reminder: {a} % {b} = {a%b}")
print(f"Floor division: {a} // {b} = {a//b}")
# print(f"Exponent: {a} ** {b} = {a**b}")
